### ISSUE TITLE
[Translation] Menu Меню

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#23]
(e.g. on https://theyvoteforyou.org.au/) 

<table class="c23" cellpadding="0" cellspacing="0"><tbody><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c3">English Version</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c3">Ukrainian Version</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c3">Note</span></p></td></tr></strong><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">They Vote For You</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Вони голосують для тебе</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">What will be the site’s brand in Ukrainian?</span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">People</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Депутати</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Deputies?</span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Policies</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Політики</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Divisions</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Голосування</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Votes?</span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">About</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Про нас</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Log In</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Увійти</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Not sure if this is a priority feature at this stage, unless it’s for Opora staff to update policy info, etc.</span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c42"><del>Sign up</del></span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Ditto</span></p></td></tr><tr class="c12"><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Search</span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0"><span class="c2">Пошук </span></p></td><td class="c4" colspan="1" rowspan="1"><p class="c0 c11"><span class="c2"></span></p></td></tr></tbody></table>

## TODO
- [x] [Title labels](https://github.com/OPORA/publicwhip/blob/develop/app/views/layouts/application.html.haml#L40-L43) on links
- [x] Search [submit button](https://github.com/OPORA/publicwhip/blob/develop/app/views/layouts/application.html.haml#L52) text (only shown on screen readers)
- [x] ["Expand navigation"](https://github.com/OPORA/publicwhip/blob/develop/app/views/layouts/application.html.haml#L31) text on nav button
- [x] [Site slogan](https://github.com/OPORA/publicwhip/blob/develop/app/views/layouts/application.html.haml#L15) - "How does your MP vote?"

**Comment by henare** [comment]
Apart from the above TODOs, all these changes have been made and are now visible https://tvfy-ukraine.oaf.org.au/

@mmitre @lisoffsky can you please provide the translations in the TODO? Please let us know if they're not clear.

**Comment by mmitre** [comment]
Added strings to translation document for Olena to translate.

Can you provide a bit more context for "Expand navigation?"

**Comment by henare** [comment]
> Added strings to translation document for Olena to translate.

:ok_hand: great stuff!

> Can you provide a bit more context for "Expand navigation?"

At small screen sizes the menu becomes a dropdown:

![selection_001](https://cloud.githubusercontent.com/assets/48945/11136716/30dca784-8a05-11e5-8901-9717c79b1b41.png)

The phrase "Expand navigation" is read to people using screen readers so they know to click it to expand the navigation menu.
