### ISSUE TITLE
[translation] Policies Політики

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#28]
Policies Політики

(https://theyvoteforyou.org.au/policies)

<table cellpadding="0" cellspacing="0" class="c10"><tbody><tr class="c15"><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c18">English Version</span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c18">Ukrainian Version</span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c18">Notes</span></p></td></tr><tr class="c15"><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">Policies</span></p><p class="c3"><span class="c1">Policies are a group of votes which, taken together, indicate a particular stance on an issue. You can research and create your own.</span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">Політики</span></p><p class="c3"><span class="c1">Політики - це перелік &nbsp;голосувань за законопроект/пакет пов’язаних законопроектів, які у сукупності виступають за впровадження у дію конкретної позиції з певного питання. Ти можеш запропонувати свою власну політику.</span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3 c16"><span class="c1"></span></p></td></tr><tr class="c15"><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">New policy</span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">Нова політика </span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">Not a priority for Opora right now for other people to propose policies? (see #27 )</span></p></td></tr><tr class="c15"><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">X divisions</span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">X голосувань </span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">X votes</span></p></td></tr><tr class="c15"><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">edited X months ago</span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">редаговано Х місяців тому </span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3 c16"><span class="c1"></span></p></td></tr><tr class="c15"><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">edited about X ago</span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">редаговано близько Х років тому </span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3 c16"><span class="c1"></span></p></td></tr><tr class="c15"><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">See also draft policies</span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">Дивитись проекти політик </span></p></td><td class="c0" colspan="1" rowspan="1"><p class="c3"><span class="c1">Not a priority? Yes (see #27 )</span></p></td></tr></tbody></table>

## TODOs
- [x] Translate "A list of policies available on Вони голосують для тебе" in [the page <meta> description](https://github.com/OPORA/publicwhip/blob/develop/app/views/policies/index.html.haml#L2).
- [x] What part of ["See also draft policies."](https://github.com/OPORA/publicwhip/blob/develop/app/views/policies/index.html.haml#L20) Should be linked?
- [ ] How does 'division' get pluralised? The Ukrainian version of "1 division" or "2 division**s**". Is this an issue? of does "1 голосувань" and "5 голосувань" both make sense?
- [x] translation for "X unedited":
  ![screen shot 2015-11-11 at 4 49 29 pm](https://cloud.githubusercontent.com/assets/1239550/11084853/4a5c2b3e-8894-11e5-87ee-285961d0e98e.png)
- [x] translation of [`time_ago_in_words`](http://apidock.com/rails/ActionView/Helpers/DateHelper/time_ago_in_words) output for ["edited about 2 months ago"](https://github.com/OPORA/publicwhip/blob/develop/app/views/policies/_policies_list.html.haml#L15). – looks like i18n can help with this does this, [see example in Stackoverflow discussion](http://stackoverflow.com/questions/19158293/rails-i18n-distance-of-time-in-words-to-now)

**Comment by equivalentideas** [comment]
Apart from the TODOs above, this page is done by https://github.com/OPORA/publicwhip/compare/fc605b9d48a3...78a2a2780a0c:
![screen shot 2015-11-11 at 4 54 11 pm](https://cloud.githubusercontent.com/assets/1239550/11084897/e13c902a-8894-11e5-9d01-3d66394d465d.png)

Could you please provide the translations for the above TODOs, apart from the last one @mmitre @lisoffsky ? Let me know if any of my notes are confusing. Thanks :star2:

**Comment by mmitre** [comment]
Translate "A list of policies available on Вони голосують для тебе"
[MM] Added to translation doc for Olena to translate

What part of "See also draft policies." Should be linked?
[MM] проекти політик

How does 'division' get pluralised? The Ukrainian version of "1 division" or "2 divisions". Is this an issue? of does "1 голосувань" and "5 голосувань" both make sense?
[MM] Added question to translation doc for Olena to respond

translation for "X unedited"
[MM] Added to translation doc for Olena to translate

translation of time_ago_in_words output for "edited about 2 months ago"
[MM] Added to translation doc for Olena to translate, for days, months and years. Do we need any other unit of time?

**Comment by orybiy** [comment]
Translate "A list of policies available on Вони голосують для тебе"
Перелік політик, доступних на сайті

How does 'division' get pluralised? The Ukrainian version of "1 division" or "2 divisions". Is this an issue? of does "1 голосувань" and "5 голосувань" both make sense?
1-4 "голосування" but 5+ "голосувань'.

translation for "X unedited"
Х у розробці

translation of time_ago_in_words output for "edited about 2 months ago"
редаговано близько 2 місяців тому 

1 [day/month/year] ago
1 [день/місяць/рік] тому
[2 - 4] [days/months/years] ago
2-4 [дні/місяці/роки] тому
[5+] [days/months/years] ago
5+ [днів/місяців/років] тому

**Comment by equivalentideas** [comment]
Thanks @orybiy and @mmitre
